// <auto-generated />
using System;
using System.Collections.Generic;
using HealthcareInfrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthcareInfrastructure.Migrations
{
    [DbContext(typeof(PatientContext))]
    [Migration("20251108155935_iamidiot")]
    partial class iamidiot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentDate");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("patient_appointments", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointmentCancellation", b =>
                {
                    b.Property<Guid>("CancellationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CancellationId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("patient_appointment_cancellations", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointmentDetail", b =>
                {
                    b.Property<Guid>("AppointmentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ReasonForVisit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TreatmentPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("AppointmentDetailId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("patient_appointment_details", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointmentReminder", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("ReminderMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ReminderId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("patient_appointment_reminders", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientAllergy", b =>
                {
                    b.Property<Guid>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AllergyId");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("patient_allergies", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientMedicalRecord", b =>
                {
                    b.Property<Guid>("MedicalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AlcoholConsumption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("BMI")
                        .HasColumnType("double precision");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<double>("HeightInCm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SmokingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("double precision");

                    b.HasKey("MedicalRecordId");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_medical_records", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientMedication", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("MedicationId");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("patient_medications", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.AddressLocation", b =>
                {
                    b.Property<Guid>("AddressLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AddressLocationId");

                    b.HasIndex("City");

                    b.HasIndex("Country");

                    b.HasIndex("PatientAddressId")
                        .IsUnique();

                    b.ToTable("address_locations", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.HasIndex("DateOfBirth");

                    b.HasIndex("PatientId");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("patients", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientAddress", b =>
                {
                    b.Property<Guid>("PatientAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Address1Type")
                        .HasColumnType("integer");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<int?>("Address2Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("PatientAddressId");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_addresses", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientAudit", b =>
                {
                    b.Property<Guid>("PatientAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("PatientAuditId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("patient_audits", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientContact", b =>
                {
                    b.Property<Guid>("PatientContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientContactId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("patient_contacts", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientTreatmentPlan", b =>
                {
                    b.Property<Guid>("TreatmentPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FollowUpInstructions")
                        .HasColumnType("text");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("PrescribedMedications")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("RecommendedTests")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreatmentDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("TreatmentPlanId");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_treatment_plans", "patient_management");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointment", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointmentCancellation", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointment", null)
                        .WithOne("AppointmentCancellation")
                        .HasForeignKey("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointmentCancellation", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointmentDetail", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointment", null)
                        .WithOne("AppointmentDetail")
                        .HasForeignKey("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointmentDetail", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientTreatmentPlan", "TreatmentPlan")
                        .WithMany()
                        .HasForeignKey("TreatmentPlanId");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointmentReminder", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointment", null)
                        .WithMany("AppointmentReminders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientAllergy", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientMedicalRecord", null)
                        .WithMany("Allergies")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientMedicalRecord", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.Patient", null)
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientMedication", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientMedicalRecord", null)
                        .WithMany("Medications")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.AddressLocation", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientAddress", null)
                        .WithOne("Location")
                        .HasForeignKey("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.AddressLocation", "PatientAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientAddress", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.Patient", null)
                        .WithMany("Addresses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientAudit", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.Patient", null)
                        .WithOne("Audits")
                        .HasForeignKey("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientAudit", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientContact", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.Patient", null)
                        .WithOne("Contact")
                        .HasForeignKey("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientContact", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientTreatmentPlan", b =>
                {
                    b.HasOne("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientAppointment.PatientAppointment", b =>
                {
                    b.Navigation("AppointmentCancellation");

                    b.Navigation("AppointmentDetail");

                    b.Navigation("AppointmentReminders");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientMedRecord.PatientMedicalRecord", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Medications");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.Patient", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Audits")
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("HealthcareModel.Models.PatientManagement.PatientPersonalnfo.PatientAddress", b =>
                {
                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
